// Generated by CoffeeScript 1.4.0
(function() {

  define(['jquery', 'primedia_events', 'utils'], function($, events, utils) {
    var _read, _write;
    _read = function(key) {
      var data;
      data = localStorage.getItem(key);
      if (data != null) {
        return JSON.parse(data);
      } else {
        return null;
      }
    };
    _write = function(key, value) {
      localStorage.setItem(key, JSON.stringify(value));
      return value;
    };
    return {
      path: function() {
        return window.location.pathname;
      },
      path_and_query: function() {
        return window.location.pathname + window.location.search;
      },
      key: function(type) {
        var refinements;
        if (type == null) {
          type = "refined";
        }
        switch (type) {
          case "refined":
            return this.path();
          case "base":
            refinements = $("head meta[name='refinements']").attr('content') || "";
            return this.path().split(refinements).shift();
        }
      },
      track: function() {
        var count;
        count = this.peek('count', 0) + 1;
        return this.save('count', count);
      },
      save: function(item, value) {
        var data, key, record;
        key = this.key();
        data = utils.getPageInfo(key);
        record = _read(key) || data;
        record[item] = value;
        _write(key, record);
        return record;
      },
      peek: function(item, not_found) {
        var v;
        if (not_found == null) {
          not_found = 0;
        }
        v = _read(this.key()) || {};
        if (v[item] != null) {
          return v[item];
        } else {
          return not_found;
        }
      },
      number_of_visits: function() {
        return this.peek('count');
      },
      refinements: function() {
        return this.peek('nodes', []);
      },
      number_of_refinements: function() {
        return this.peek('nodes', []).length;
      },
      type: function() {
        return this.peek('type', '');
      },
      searchType: function() {
        return this.peek('searchType', '');
      }
    };
  });

}).call(this);
