// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  define(['flight/lib/component', 'marker-clusterer', 'utils'], function(defineComponent, markerClusterer, Utils) {
    var initMarkerClusters;
    initMarkerClusters = function() {
      this.defaultAttrs({
        mapPinCluster: Utils.assetURL() + "/images/nonsprite/map/map_cluster_red4.png",
        markerClusterer: void 0
      });
      this.clearMarkers = function() {
        this.unbindMarkers;
        return this.attr.markers.clearMarkers();
      };
      this.unbindMarkers = function() {
        return $.each(this.attr.markerClusterer, function(index, marker) {
          return google.maps.event.clearListeners(marker, "click");
        });
      };
      this.mapClusterOptions = function() {
        var style;
        style = {
          height: 40,
          url: this.attr.mapPinCluster,
          width: 46,
          textColor: "black"
        };
        return {
          styles: [style, style, style, style, style],
          minimumClusterSize: 5
        };
      };
      this.initClusterer = function(ev, data) {
        return this.attr.markerClusterer = new MarkerClusterer(data.gMap, [], this.mapClusterOptions());
      };
      return this.after('initialize', function() {
        return this.on(document, 'mapRenderedFirst', this.initClusterer);
      });
    };
    return initMarkerClusters;
  });

}).call(this);
