// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  define(['flight/lib/component', 'utils'], function(defineComponent, utils) {
    var infoWindow;
    infoWindow = function() {
      ({
        currentOpenWindow: null,
        eventsWired: false
      });
      this.defaultAttrs({
        gMap: {},
        gMarker: {}
      });
      this.showInfoWindowOnMarkerClick = function(ev, data) {
        this.attr.gMarker = data.gMarker;
        this.attr.gMap = data.gMap;
        return this.trigger(document, 'uiInfoWindowDataRequest', {
          listingId: this.attr.gMarker.datumId
        });
      };
      this.render = function(ev, data) {
        this.closeOpenInfoWindow();
        this.openInfoWindow(data);
        return this.wireUpEvents();
      };
      this.closeOpenInfoWindow = function() {
        if (this.currentOpenWindow) {
          return this.currentOpenWindow.close();
        }
      };
      this.openInfoWindow = function(data) {
        if (!this.currentOpenWindow) {
          this.currentOpenWindow = new google.maps.InfoWindow();
        }
        this.currentOpenWindow.setContent(data);
        return this.currentOpenWindow.open(this.attr.gMap, this.attr.gMarker);
      };
      this.wireUpEvents = function() {
        if (this.currentOpenWindow && !this.eventsWired) {
          google.maps.event.addListener(this.currentOpenWindow, 'closeclick', function() {
            return $(document).trigger('uiInfoWindowClosed');
          });
          return this.eventsWired = true;
        }
      };
      return this.after('initialize', function() {
        this.on(document, 'markerClicked', this.showInfoWindowOnMarkerClick);
        this.on(document, 'infoWindowDataAvailable', this.render);
        return this.on(document, 'uiCloseOpenInfoWindows', this.closeOpenInfoWindow);
      });
    };
    return infoWindow;
  });

}).call(this);
