// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  define(['flight/lib/component', 'map/ui/markers', 'map/ui/info_window'], function(defineComponent, Markers, InfoWindow) {
    var markersInfoWindow;
    markersInfoWindow = function() {
      return this.after('initialize', function() {
        return Markers.attachTo(this.node);
      });
    };
    return defineComponent(markersInfoWindow, InfoWindow);
  });

}).call(this);
