// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  define(['underscore', 'flight/lib/component', 'lib/fusiontip/fusiontip', 'lib/accounting/accounting', 'map/utils/mobile_detection'], function(_, defineComponent, fusionTip, accounting, mobileDetection) {
    var neighborhoodsOverlay;
    neighborhoodsOverlay = function() {
      this.defaultAttrs({
        enableOnboardCalls: false,
        enableMouseover: false,
        tableId: void 0,
        apiKey: void 0,
        hoodLayer: void 0,
        gMap: void 0,
        toggleLink: void 0,
        toggleControl: void 0,
        data: void 0,
        infoTemplate: void 0,
        tipStyle: '',
        mouseTipDelay: 200,
        suppressMapTips: false,
        minimalZommLevel: 12,
        polyOptions: {
          clicked: {
            strokeColor: "#000",
            strokeOpacity: .5,
            strokeWeight: 1,
            fillColor: "#000",
            fillOpacity: .2
          },
          mouseover: {
            strokeColor: "#000",
            strokeOpacity: .5,
            strokeWeight: 1,
            fillColor: "#000",
            fillOpacity: .2
          },
          mouseout: {
            strokeWeight: 0,
            fillOpacity: 0
          }
        },
        polygonOptions: {
          fillColor: "BC8F8F",
          fillOpacity: 0.1,
          strokeColor: "4D4D4D",
          strokeOpacity: 0.8,
          strokeWeight: 1
        },
        polygonOptionsCurrent: {
          fillOpacity: 0.5,
          strokeColor: '4D4D4D',
          strokeOpacity: 0.7,
          strokeWeight: 2
        },
        infoWindowData: {
          state: void 0,
          hood: void 0,
          population: void 0,
          growth: void 0,
          density: void 0,
          males: void 0,
          females: void 0,
          median_income: void 0,
          average_income: void 0
        }
      });
      this.infoWindow = new google.maps.InfoWindow();
      this.hoodQuery = function(data) {
        var where;
        return where = "LATITUDE >= " + data.lat1 + " AND LATITUDE <= " + data.lat2 + " AND LONGITUDE >= " + data.lng1 + " AND LONGITUDE <= " + data.lng2;
      };
      this.addHoodsLayer = function(ev, data) {
        if (!data || !data.gMap || data.gMap.getZoom() < this.attr.minimalZommLevel) {
          return;
        }
        this.attr.gMap = data.gMap;
        this.attr.data = data;
        this.setupLayer(data);
        this.attr.hoodLayer.setMap(this.attr.gMap);
        return this.setupMouseOver();
      };
      this.setupMouseOver = function() {
        if (!this.isMobile() && this.attr.enableMouseover) {
          return this.buildMouseOverWindow();
        }
      };
      this.setupLayer = function(data) {
        var query;
        query = this.hoodQuery(data);
        if (this.attr.hoodLayer != null) {
          this.attr.hoodLayer.setMap(null);
          return this.attr.hoodLayer.setQuery(query);
        } else {

        }
      };
      this.getData = function(data) {
        var body, encodedQuery, query, script, url;
        script = document.createElement("script");
        url = ["https://www.googleapis.com/fusiontables/v1/query?"];
        url.push("sql=");
        query = "SELECT geometry, HOOD_NAME, STATENAME, MARKET FROM " + this.attr.tableId;
        encodedQuery = encodeURIComponent(query);
        url.push(encodedQuery);
        url.push("&callback=drawMap");
        url.push("&key=AIzaSyAm9yWCV7JPCTHCJut8whOjARd7pwROFDQ");
        script.src = url.join("");
        body = document.getElementsByTagName("body")[0];
        return body.appendChild(script);
      };
      this.drawMap = function(data) {
        var country, geometries, i, j, newCoordinates, randomnumber, rows, _results;
        rows = data["rows"];
        _results = [];
        for (i in rows) {
          if (rows[i][0] !== "Antarctica") {
            newCoordinates = [];
            geometries = rows[i][1]["geometries"];
            if (geometries) {
              for (j in geometries) {
                newCoordinates.push(this.constructNewCoordinates(geometries[j]));
              }
            } else {
              newCoordinates = this.constructNewCoordinates(rows[i][1]["geometry"]);
            }
            randomnumber = Math.floor(Math.random() * 4);
            country = new google.maps.Polygon({
              paths: newCoordinates,
              strokeColor: colors[randomnumber],
              strokeOpacity: 0,
              strokeWeight: 1,
              fillColor: colors[randomnumber],
              fillOpacity: 0.3
            });
            google.maps.event.addListener(country, "mouseover", function() {
              return this.setOptions({
                fillOpacity: 1
              });
            });
            google.maps.event.addListener(country, "mouseout", function() {
              return this.setOptions({
                fillOpacity: 0.3
              });
            });
            _results.push(country.setMap(this.attr.gMap));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };
      this.constructNewCoordinates = function(polygon) {
        var coordinates, i, newCoordinates;
        newCoordinates = [];
        coordinates = polygon["coordinates"][0];
        for (i in coordinates) {
          newCoordinates.push(new google.maps.LatLng(coordinates[i][1], coordinates[i][0]));
        }
        return newCoordinates;
      };
      this.parseRow = function(row) {};
      this.setupToggle = function() {
        this.positionToggleControl();
        return this.setupToggleAction();
      };
      this.setupToggleAction = function() {
        if (this.attr.toggleLink) {
          return this.on(this.attr.toggleLink, 'click', this.toggleLayer);
        }
      };
      this.positionToggleControl = function() {
        var control;
        if (this.attr.toggleControl) {
          control = $('<div/>');
          control.append($(this.attr.toggleControl));
          return this.attr.gMap.controls[google.maps.ControlPosition.TOP_RIGHT].push(control[0]);
        }
      };
      this.toggleLayer = function() {
        if (this.attr.hoodLayer.getMap()) {
          return this.attr.hoodLayer.setMap(null);
        } else {
          this.attr.hoodLayer.setMap(this.attr.gMap);
          return this.setupMouseOver();
        }
      };
      this.buildMouseOverWindow = function() {
        return this.attr.hoodLayer.enableMapTips({
          select: "HOOD_NAME",
          from: this.attr.tableId,
          geometryColumn: "geometry",
          suppressMapTips: this.attr.suppressMapTips,
          delay: this.attr.mouseTipDelay,
          tolerance: 8,
          key: this.attr.apiKey,
          style: this.attr.tipStyle
        });
      };
      this.addListeners = function() {
        var _this = this;
        if (this.attr.infoTemplate) {
          return google.maps.event.addListener(this.attr.hoodLayer, 'click', function(e) {
            return $(document).trigger('neighborhoodClicked', {
              row: e.row,
              location: e.latLng
            });
          });
        }
      };
      this.buildInfoWindow = function(event, data) {
        this.trigger(document, 'uiNHoodInfoWindowDataRequest');
        this.buildInfoData(event, data);
        event.infoWindowHtml = _.template(this.attr.infoTemplate, this.attr.infoWindowData);
        this.infoWindow.setContent(event.infoWindowHtml);
        this.infoWindow.setPosition(data.location);
        return this.infoWindow.open(this.attr.gMap);
      };
      this.buildInfoData = function(event, data) {
        var row;
        row = data.row;
        if (!_.isEmpty(row)) {
          this.attr.infoWindowData.state = row.STATENAME.value;
          this.attr.infoWindowData.hood = row.HOOD_NAME.value;
          return this.buildOnboardData(row);
        }
      };
      this.buildOnboardData = function(row) {
        var data, demographic, key, value, _ref, _results;
        if (!this.attr.enableOnboardCalls) {
          return;
        }
        data = JSON.parse(this.getOnboardData(row).responseText);
        if (!_.isEmpty(data)) {
          demographic = data.demographic;
          _ref = this.attr.infoWindowData;
          _results = [];
          for (key in _ref) {
            value = _ref[key];
            if (demographic[key]) {
              _results.push(this.attr.infoWindowData[key] = this.formatValue(key, demographic[key]));
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        }
      };
      this.formatValue = function(key, value) {
        switch (key) {
          case 'median_income':
          case 'average_income':
            return accounting.formatMoney(value);
          case 'population':
            return accounting.formatNumber(value);
          default:
            return value;
        }
      };
      this.getOnboardData = function(row) {
        var query, xhr;
        if (_.isEmpty(row)) {
          return {};
        }
        query = [];
        query.push("state=" + (this.toDashes(row.STATENAME.value)));
        query.push("city=" + (this.toDashes(row.MARKET.value)));
        query.push("neighborhood=" + (this.toDashes(row.HOOD_NAME.value)));
        return xhr = $.ajax({
          url: "/meta/community?rectype=NH&" + (query.join('&')),
          async: false
        }).done(function(data) {
          return data;
        }).fail(function(data) {
          return {};
        });
      };
      this.toDashes = function(value) {
        if (value == null) {
          return '';
        }
        return value.replace(' ', '-');
      };
      this.toSpaces = function(value) {
        if (value == null) {
          return '';
        }
        return value.replace('-', ' ');
      };
      return this.after('initialize', function() {
        this.on(document, 'uiNeighborhoodDataRequest', this.addHoodsLayer);
        this.on(document, 'neighborhoodClicked', this.buildInfoWindow);
      });
    };
    return defineComponent(neighborhoodsOverlay, mobileDetection);
  });

}).call(this);
