// Generated by CoffeeScript 1.6.3
(function() {
  define(['underscore'], function(_) {
    var generateTooltip;
    generateTooltip = function() {
      this.constructor = function() {
        this.ToolTip = new google.maps.OverlayView;
        this.container = $("<div/>", {
          "class": "hood_info_window"
        });
        this.position = null;
        this.count = null;
        this.listener = void 0;
        return this.offset = {
          x: 20,
          y: 20
        };
      };
      this.destroy = function() {
        return this.setMap(null);
      };
      this.onAdd = function() {
        return this.container.appendTo(this.getPanes().floatPane);
      };
      this.onRemove = function() {
        return this.container.remove();
      };
      this.setContent = function(data) {
        this.container.html(_.template(this.attr.infoTemplate, data));
        return this.ToolTip.setMap(this.attr.gMap);
      };
      this.hide = function() {
        this.container.hide().empty();
        return google.maps.event.removeListener(this.listener);
      };
      this.show = function() {
        return this.container.show();
      };
      this.onMouseMove = function(latLng) {
        var px;
        px = this.ToolTip.getProjection().fromLatLngToContainerPixel(latLng);
        return this.container.css({
          left: px.x + this.offset.x,
          top: px.y + this.offset.y
        });
      };
      this.updatePosition = function(position, overlay) {
        var _this = this;
        return this.listener = google.maps.event.addListener(overlay, "mousemove", function(event) {
          _this.onMouseMove(event.latLng, overlay);
          return _this.show();
        });
      };
      return this.after('initialize', function() {
        return this.on(document, 'neighborhoodsAvailable', this.constructor);
      });
    };
    return generateTooltip;
  });

}).call(this);
