// Generated by CoffeeScript 1.6.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(['jquery', 'jquery-cookie-rjs'], function($) {
  var LeadForm;
  LeadForm = (function() {
    function LeadForm(container) {
      this.container = container;
      this.submit = __bind(this.submit, this);
      this.form = this.container.find('#lead_form');
      this.errorMsg = this.container.find('.full_errors');
      this.form.submit(this.submit);
      this.updateFormByCookie();
      this.showOptionalFields();
    }

    LeadForm.prototype.getSessionID = function() {
      if ((typeof WH !== "undefined" && WH !== null ? WH.userID : void 0) && (typeof WH !== "undefined" && WH !== null ? WH.sessionID : void 0)) {
        return "" + WH.userID + "." + WH.sessionID;
      } else {
        return "no_session_id_" + (new Date().getTime());
      }
    };

    LeadForm.prototype.getWebsite = function() {
      return window.location.host;
    };

    LeadForm.prototype.showOptionalFields = function() {
      var optional, required;
      if ($('#lead_optional_fields').length) {
        optional = $('#lead_optional_fields').val().split(',');
      } else {
        optional = [];
      }
      if ($('#lead_required_fields').length) {
        required = $('#lead_required_fields').val().split(',');
      } else {
        required = [];
      }
      return $(optional.concat(required)).each(function(index, element) {
        return $(".lead_" + element).show();
      });
    };

    LeadForm.prototype.saveDataToCookie = function() {
      var data;
      if (!(typeof JSON && typeof JSON.stringify)) {
        return;
      }
      data = {
        firstName: this.form.find('#lead_first_name').val(),
        lastName: this.form.find('#lead_last_name').val(),
        email: this.form.find('#lead_email').val(),
        phone: this.form.find('#lead_phone').val(),
        beds: this.form.find('#lead_beds').val(),
        baths: this.form.find('#lead_baths').val(),
        message: this.form.find('#lead_message').val()
      };
      return $.cookie("lead", JSON.stringify(data));
    };

    LeadForm.prototype.updateFormByCookie = function() {
      var data;
      if (!$.cookie("lead")) {
        return;
      }
      data = $.parseJSON($.cookie("lead"));
      if (!(typeof data === 'object')) {
        return;
      }
      this.form.find("#lead_first_name").val(data.firstName);
      this.form.find("#lead_last_name").val(data.lastName);
      this.form.find("#lead_email").val(data.email);
      this.form.find("#lead_phone").val(data.phone);
      this.form.find("#lead_message").val(data.message);
      this.form.find("#lead_beds").val(data.beds);
      this.form.find("#lead_baths").val(data.baths);
      this.form.find("#lead_session_id").val(this.getSessionID());
      return this.form.find('#lead_website').val(this.getWebsite());
    };

    LeadForm.prototype.thankYouTemplate = function() {
      return "<div id=\"lead_thank_you\">\n  <h2>Thank you for your inquiry.</h2>\n  <p>The information you provided will be sent to the appropriate location. If you have additional questions, contact the property at the number provided.</p>\n</div>";
    };

    LeadForm.prototype.submit = function(e) {
      var _this = this;
      e.preventDefault();
      this.saveDataToCookie();
      return $.ajax({
        type: 'POST',
        url: this.form.attr("action"),
        data: this.form.serialize()
      }).done(function() {
        _this.container.html(_this.thankYouTemplate());
        return $(document).trigger('leadservice:success');
      }).fail(function(res) {
        var responseText;
        responseText = $(res.responseText);
        _this.errorMsg.html(responseText.find('.full_errors').html());
        return $(document).trigger('leadservice:fail');
      });
    };

    return LeadForm;

  })();
  return $(function() {
    return new LeadForm($('#lead_form_container'));
  });
});
