// Generated by CoffeeScript 1.6.3
(function() {
  describe("Zutron", function() {
    var zutron;
    zutron = void 0;
    beforeEach(function() {
      var ready;
      ready = false;
      jasmine.getGlobal().zutron_host = "http://test.com";
      require(['../../zutron-common', 'jasmine-jquery'], function(_zutron, $) {
        zutron = _zutron;
        return ready = true;
      });
      return waitsFor(function() {
        return ready;
      });
    });
    return describe("functionality", function() {
      it("is defined", function() {
        return expect(zutron).toBeDefined();
      });
      return it("should get data for zid", function() {
        spyOn($, "ajax").andCallFake(function(req) {
          var d;
          d = $.Deferred();
          d.resolve({
            zid: {
              key: "asdf",
              listings: []
            }
          });
          return d.promise();
        });
        zutron.getSavedListings();
        return $.fn.on("zutron/savedListings", function(data) {
          return expect(data).toBeDefined();
        });
      });
    });
  });

}).call(this);
