// Generated by CoffeeScript 1.6.3
(function() {
  describe("Zutron", function() {
    var zutron;
    zutron = void 0;
    beforeEach(function() {
      var ready;
      ready = false;
      require(['../../zutron-common', 'jasmine-jquery'], function(_zutron) {
        zutron = _zutron;
        return ready = true;
      });
      return waitsFor(function() {
        return ready;
      });
    });
    return describe("zutron", function() {
      return it("is defined", function() {
        return expect(zutron).toBeDefined();
      });
    });
  });

}).call(this);
