// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  define(['common/ag-utils', 'common/virtual-tour'], function(utils, virtualTour) {
    var initVirtualTours, setPhotoPlusSlideShow, _setListingId, _warehousePhotoTracking;
    setPhotoPlusSlideShow = function() {
      $('.photoplus').photoplus();
      return _warehousePhotoTracking();
    };
    initVirtualTours = function() {
      return $('.link_icon_virtual').each(function() {
        return virtualTour.setupTour($(this));
      });
    };
    _warehousePhotoTracking = function() {
      var _this = this;
      $('.scrollingHotSpotLeft, .scrollingHotSpotRight').bind('click', function(e) {
        var $imageContainer, listingId;
        listingId = $(e.target).closest('.column1').find('a.link_icon_photos').attr('data-listingid');
        $imageContainer = $(e.target).closest('.column1').find('.scrollableArea');
        _setListingId($imageContainer, listingId);
        return WH.fire({
          sg: 'scrollableArea',
          item: 'scrollablePhoto',
          type: 'click',
          listingId: listingId
        });
      });
      return utils.slideshowTracking();
    };
    _setListingId = function(imageContainer, listingId) {
      var images;
      images = $(imageContainer).find('img');
      return $(images).each(function() {
        $(this).attr('class', 'photo');
        return $(this).attr('data-listingid', listingId);
      });
    };
    return {
      setPhotoPlusSlideShow: setPhotoPlusSlideShow,
      initVirtualTours: initVirtualTours
    };
  });

}).call(this);
