// Generated by CoffeeScript 1.7.0
(function() {
  define(['jquery'], function($) {
    return {
      assetURL: function() {
        return $('meta[name="asset_host"]').attr('content');
      },
      hideSpinner: function() {
        return $('.spinner').hide();
      }
    };
  });

}).call(this);
