// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery'], function($) {
    return {
      assetURL: function() {
        return $('meta[name="asset_host"]').attr('content');
      },
      hideSpinner: function() {
        return $('.spinner').hide();
      },
      limitScaleOf: function(number, limit) {
        if (limit == null) {
          limit = 4;
        }
        return number.toFixed(limit);
      }
    };
  });

}).call(this);
