// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    return {
      assetURL: function() {
        return $('meta[name="asset_host"]').attr('content');
      },
      hideSpinner: function() {
        return $('.spinner').hide();
      }
    };
  });

}).call(this);
