// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery'], function($) {
    var assetHostMetaKey, assetURL, currentServerIndex, isInvalidURL, notFoundPath, notFoundURL, pickServer, servers, serversMetaKey, setNotFoundPath, url, _contentFromMeta;
    serversMetaKey = "image_server_urls";
    servers = null;
    currentServerIndex = -1;
    notFoundPath = "";
    assetHostMetaKey = "asset_host";
    isInvalidURL = function(images) {
      return typeof images === 'undefined' || images.length === 0;
    };
    url = function(images, w, h) {
      var path, pathParts, queryString;
      if (isInvalidURL(images)) {
        return notFoundURL();
      }
      path = $.isArray(images) ? images[0].path : images;
      if (path[0] !== '/') {
        path = '/' + path;
      }
      url = pickServer();
      pathParts = path.split('?');
      path = pathParts[0];
      queryString = pathParts.length > 1 ? '?' + pathParts[1] : '';
      if (path.substr(-1) !== '/') {
        path += '/';
      }
      if (w) {
        path += w;
      }
      if (w || h) {
        path += "-";
      }
      if (h) {
        path += h;
      }
      url += path + queryString;
      return url;
    };
    _contentFromMeta = function(metaTag) {
      var content;
      content = metaTag.attr('content');
      return (content || "").split(',');
    };
    pickServer = function() {
      if (servers == null) {
        servers = _contentFromMeta($("meta[name=\"" + serversMetaKey + "\"]"));
      }
      currentServerIndex += 1;
      return servers[currentServerIndex % servers.length];
    };
    assetURL = function() {
      return $("meta[name=\"" + assetHostMetaKey + "\"]").attr('content');
    };
    notFoundURL = function() {
      return "" + (assetURL()) + notFoundPath;
    };
    setNotFoundPath = function(path) {
      return notFoundPath = path;
    };
    return {
      isInvalidURL: isInvalidURL,
      url: url,
      pickServer: pickServer,
      assetURL: assetURL,
      notFoundURL: notFoundURL,
      setNotFoundPath: setNotFoundPath,
      servers: servers,
      _contentFromMeta: _contentFromMeta
    };
  });

}).call(this);
