// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'underscore'], function($, _) {
    var assetURL, imageServerCount, isInvalidURL, nextImageServer, notFoundURL, pickImageServer, url;
    imageServerCount = 2;
    nextImageServer = 0;
    isInvalidURL = function(photoList) {
      return typeof photoList === 'undefined' || photoList.length === 0;
    };
    url = function(photoList, w, h) {
      var path, pathParts, queryString;
      if (isInvalidURL(photoList)) {
        return notFoundURL();
      }
      path = $.isArray(photoList) ? _.first(photoList).path : photoList;
      if (path[0] !== '/') {
        path = '/' + path;
      }
      url = "http://image" + pickImageServer() + ".apartmentguide.com";
      pathParts = path.split('?');
      path = pathParts[0];
      queryString = pathParts.length > 1 ? '?' + pathParts[1] : '';
      if (path.substr(-1) !== '/') {
        path += '/';
      }
      if (w || h) {
        if (w) {
          path += w;
        }
        path += "-";
        if (h) {
          path += h;
        }
      }
      url += path + queryString;
      return url;
    };
    pickImageServer = function() {
      nextImageServer += 1;
      if (nextImageServer >= imageServerCount) {
        nextImageServer = 0;
      }
      if (nextImageServer) {
        return nextImageServer;
      } else {
        return '';
      }
    };
    assetURL = function() {
      return $('meta[name="asset_host"]').attr('content');
    };
    notFoundURL = function() {
      return assetURL() + "/images/prop_no_photo_results.png";
    };
    return {
      assetURL: assetURL,
      isInvalidURL: isInvalidURL,
      url: url,
      pickImageServer: pickImageServer,
      notFoundURL: notFoundURL
    };
  });

}).call(this);
