// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'es5-shim/lib/es5-shim', 'es5-shim/lib/es5-sham', 'flight/lib/utils', 'map/ui/base_map', 'map/ui/markers_info_window', 'map/ui/search_map_by_address'], function($, es5Shim, es5Sham, FlightUtils, BaseMap, MarkerInfoWindow, SearchMapByAddress) {
    var initialize;
    initialize = function() {
      var addressSearchSel, args, geoData, mapSel;
      args = FlightUtils.toArray(arguments);
      mapSel = args.shift();
      addressSearchSel = args.shift();
      geoData = args.pop();
      BaseMap.attachTo(mapSel, {
        geoData: geoData
      });
      MarkerInfoWindow.attachTo(mapSel);
      return SearchMapByAddress.attachTo(addressSearchSel);
    };
    return initialize;
  });

}).call(this);
