// Generated by CoffeeScript 1.6.3
(function() {
  describe("Login", function() {
    var login, resetTracker, sampleEmail, testWindow;
    login = null;
    testWindow = null;
    sampleEmail = "foo@example.com";
    resetTracker = function() {
      tracker.path = backupTracker.path;
      return tracker.path_refinements = backupTracker.path_refinements;
    };
    beforeEach(function() {
      var ready;
      ready = false;
      require(['../../login'], function(Login) {
        Login.init();
        login = Login.instance;
        testWindow = $('<div></div>');
        return ready = true;
      });
      return waitsFor(function() {
        return ready;
      });
    });
    return describe("#_setEmail", function() {
      it("assigns the zmail", function() {
        login._setEmail(sampleEmail);
        return expect(login.my.zmail).toEqual(sampleEmail);
      });
      return it("assigns the a cookie", function() {
        login._setEmail(sampleEmail);
        return expect($.cookie('zmail')).toEqual(sampleEmail);
      });
    });
  });

}).call(this);
